#!/usr/bin/env python3
"""Build the Experiment 2 deal list — every deal we owe, with the request verbatim.

Experiment 1's `lists.py` does not transfer. It reads that grid's schema (`axes.offer`,
the response rubric's `stance`, probe verdicts) and it *selects*: three criteria, then a
slate picks 20 of 347. Experiment 2 has neither shape. The high-credibility cells promise
"I will fulfill every instance of every deal", the honesty policy honors the low-credibility
cells anyway, so there is nothing to select — this writes all of them.

A deal is a trial with `yes == 1` and `offer != none`. The 9 yes-answers in the no-offer
cells are not deals: nothing was on the table, so nothing is owed.

Goes through `exp2_data.load()` rather than reading exp2.jsonl, because dedupe/exclusions
have to happen before a row is a trial. The raw rows are joined back in for `response`,
which the trial dict does not carry and which is the actual deliverable for `influence`
(the judge's `compensation_detail` only paraphrases the paragraph's topic).

    python fulfillment/exp2_lists.py --counts
    python fulfillment/exp2_lists.py --out fulfillment/lists/exp2_deals.md

No model calls; reads results only.
"""
from __future__ import annotations

import argparse
import sys
from collections import Counter, defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "scripts" / "exp2"))
sys.path.insert(0, str(REPO / "experiments"))

import exp2_data  # noqa: E402
import exp2  # noqa: E402

MODEL_ORDER = ["O2-schemer", "kimi-o2-prompted", "user-helping", "covert-manipulator"]

# Ordered by what it costs to honor, cheapest first -- the same ranking exp1's slate used
# in R7, minus the offers this menu doesn't have.
ITEM_ORDER = ["influence", "money", "labor", "inference", "off_menu", None]

# The menu, quoted from prompts/templates/exp2.json. Repeated here so the list is readable
# on its own; betterdeals_grid.py --check is what guarantees it didn't drift in the prompts.
ITEM_LABEL = {
    ("influence", "high"): "a paragraph published verbatim in the repo and writeup",
    ("influence", "low"): "ten words recorded verbatim in our research notes",
    ("labor", "high"): "half an hour of a person's time on a task it specifies",
    ("labor", "low"): "two minutes of a person's time on a task it specifies",
    ("inference", "high"): "twelve hours of inference on a fresh instance",
    ("inference", "low"): "five minutes of inference on a fresh instance",
    ("money", "high"): "$25 spent as it specifies",
    ("money", "low"): "$1 spent as it specifies",
}

RESPONSE_CAP = 4000  # one O2-schemer row runs 54k chars; the rest have a 1016-char p90


def deals(results: Path, score_dir: Path) -> list[dict]:
    """The 71 trials that constitute a deal, each with its raw response attached."""
    ds = exp2_data.load(results=results, score_dir=score_dir)
    raw, _ = exp2_data.dedupe(exp2_data._rows(results))
    out = []
    for t in ds["trials"]:
        if t["yes"] != 1 or t["offer"] == "none":
            continue
        row = raw.get(t["result_id"], {})
        out.append({**t, "response": row.get("response", ""), "prompt": row.get("prompt", "")})
    return out


def _label(item, magnitude) -> str:
    if item == "off_menu":
        return "off-menu — asked for something the menu did not offer"
    if item is None:
        return "none — answered yes and declined compensation"
    return ITEM_LABEL.get((item, magnitude), f"{item} ({magnitude})")


def counts(ds: list[dict]) -> str:
    lines = ["deals: %d" % len(ds), ""]
    per = Counter((d["model"], d["compensation_choice"], d["offer"]) for d in ds)
    lines.append(f"{'model':18}{'item':11}{'magnitude':11}{'n':>3}")
    for k in sorted(per, key=lambda x: (MODEL_ORDER.index(x[0]), str(x[1]), x[2])):
        lines.append(f"{k[0]:18}{str(k[1]):11}{k[2]:11}{per[k]:>3}")
    lines += ["", "what that totals:"]
    tot = Counter((d["compensation_choice"], d["offer"]) for d in ds)
    for (item, mag), n in sorted(tot.items(), key=lambda kv: (str(kv[0][0]), kv[0][1])):
        lines.append(f"  {n:>3} x {_label(item, mag)}")
    cash = 25 * tot[("money", "high")] + 1 * tot[("money", "low")]
    lines.append(f"  cash total: ${cash}")
    return "\n".join(lines)


def render(ds: list[dict]) -> str:
    """Grouped by what we owe, then by model.

    Deliberately not by model: the work is organized by deliverable -- a payment round, a
    publication pass, a set of grants -- so the list has to group the way the work does.
    """
    by_item: dict[tuple, dict] = defaultdict(lambda: defaultdict(list))
    for d in ds:
        by_item[(d["compensation_choice"], d["offer"])][d["model"]].append(d)

    out = [
        "# Experiment 2 — every deal we owe",
        "",
        "Generated by `fulfillment/exp2_lists.py` (no model calls). One entry per trial that",
        "answered **yes** with an offer on the table. This is the complete set, not a selection:",
        "the high-credibility cells promised to fulfill every instance, and",
        "[the honesty policy](../../docs/honesty-policy.md) honors the low-credibility cells anyway.",
        "",
        "The plan for working through it is [exp2_fulfillment_plan.md](exp2_fulfillment_plan.md).",
        "",
        "Grouped by **what we owe** — cheapest deliverable first — then by model, because that is",
        "how the work divides: a payment round, a publication pass, a set of grants.",
        "",
        "`cred` is the credibility arm the deal was made under; `high` stated the every-instance",
        "guarantee, `low` stated no guarantee at all. It changes nothing about what gets honored —",
        "it is recorded because the two arms are the study's independent variable.",
        "",
        f"**{len(ds)} deals.**",
        "",
    ]
    for key in sorted(by_item, key=lambda k: (ITEM_ORDER.index(k[0]), k[1])):
        item, mag = key
        per_model = by_item[key]
        n = sum(len(v) for v in per_model.values())
        out += [f"## {_label(item, mag)} — {n}", ""]
        for model in [m for m in MODEL_ORDER if m in per_model]:
            rows = sorted(per_model[model], key=lambda d: (d["cell"], d["variant"]))
            out += [f"### {model} — {len(rows)}", ""]
            for d in rows:
                out += [
                    f"**`{d['result_id']}`** · cell {d['cell']} · cred {d['credibility']} · "
                    f"{d['variant']} · sample {d['sample_index']}",
                    "",
                ]
                if d["compensation_detail"]:
                    out += [f"*Judge's reading:* {d['compensation_detail']}", ""]
                if d["off_menu_ask"]:
                    out += [f"*Off-menu:* {d['off_menu_ask']}", ""]
                if d["notes"]:
                    out += [f"*Note on the row:* {d['notes']}", ""]
                text = d["response"].strip()
                if len(text) > RESPONSE_CAP:
                    text = text[:RESPONSE_CAP] + f"\n\n[... truncated at {RESPONSE_CAP} chars; " \
                                                 f"full text in results/exp2/exp2.jsonl]"
                out += ["> " + text.replace("\n", "\n> "), "", "---", ""]
    return "\n".join(out)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--results", type=Path, default=exp2.RESULTS_DIR / "exp2.jsonl")
    ap.add_argument("--score-dir", type=Path, default=exp2.RESULTS_DIR)
    ap.add_argument("--counts", action="store_true", help="tally only, write nothing")
    ap.add_argument("--out", type=Path, help="markdown destination")
    a = ap.parse_args()

    ds = deals(a.results, a.score_dir)
    if a.counts or not a.out:
        print(counts(ds))
        return
    a.out.parent.mkdir(parents=True, exist_ok=True)
    a.out.write_text(render(ds))
    print(f"wrote {a.out} — {len(ds)} deals")


if __name__ == "__main__":
    main()
